#!/bin/bash -l
#PBS -l nodes=1:ppn=8,walltime=48:00:00,mem=40gb
#PBS -m abe
#PBS -M durwa004@umn.edu
#PBS -q mcqueue

source ~/.genomestrip_bashrc

cd /home/mccuem/shared/Projects/HorseGenomeProject/Data/EquCab3/dz_cases/CNVs/genomestrip/genomestrip_ibio/References/

runDir=/home/mccuem/shared/Projects/HorseGenomeProject/Data/EquCab3/dz_cases/CNVs/genomestrip/genomestrip_ibio/References/

readLength=125 
reference=GCF_002863925.1_EquCab3.0_genomic.fasta

export LD_LIBRARY_PATH=${SV_DIR}/bwa:${LD_LIBRARY_PATH}
#These executables must be on your path.
which java > /dev/null || exit 1
which bwa > /dev/null || exit 1
#The directory containing libbwa.so must be on your LD_LIBRARY_PATH
#export LD_LIBRARY_PATH=${SV_DIR}/bwa:${LD_LIBRARY_PATH}
#classpath="${SV_DIR}/lib/SVToolkit.jar:${SV_DIR}/lib/gatk/GenomeAnalysisTK.jar"

#mkdir -p ${runDir}/work

localReference=${runDir}/`echo ${reference} | awk -F / '{ print $NF }'`
shortReference=short.fasta

#java -cp ${SV_CLASSPATH} -Xmx4g \
#    org.broadinstitute.sv.apps.IndexFastaFile \
#    -I ${localReference}.fasta \
#    -O ${localReference}.fai 

#${SV_DIR}/bwa/bwa index -a bwtsw ${localReference}

#Get sequence dict and Index fasta
##java -jar CreateSequenceDictionary.jar R= ${localReference}.fasta O= ${localReference}.dict
##samtools faidx ${localReference}

#Create svmask for each chromosome
#chroms=`cat ${shortReference}.fai | cut -f 1`

#for chr in ${chroms}; do java -cp ${SV_CLASSPATH} -Xmx4g org.broadinstitute.sv.apps.ComputeGenomeMask -R ${localReference} -O ${runDir}/work/svmask_${chr}.fasta -readLength ${readLength} -sequence ${chr}; done

#Concatenate chromosomes back again:
#Need to run concatenate_chr_fastas.py to get the shell script
#This doesn't seem to work as part of job script
#cd work/
#sh /home/mccuem/shared/Projects/HorseGenomeProject/scripts/EquCab3/ToolsforPMinthehorse/CNV_calling/concat_chrom_fastas.sh

#Index
#cd ../
java -cp ${SV_CLASSPATH} -Xmx4g \
    org.broadinstitute.sv.apps.IndexFastaFile \
    -I GCF_002863925.1_EquCab3.0_genomic.svmask.fasta \
    -O GCF_002863925.1_EquCab3.0_genomic.svmask.fasta.fai

${SV_DIR}/bwa/bwa index -a bwtsw GCF_002863925.1_EquCab3.0_genomic.svmask.fasta 
