#!/bin/bash -l
#PBS -l nodes=1:ppn=6,walltime=24:00:00,mem=20gb
#PBS -m abe
#PBS -M durwa004@umn.edu
#PBS -q mcqueue

#cd /home/mccuem/shared/Projects/HorseGenomeProject/Data/ibio_EquCab3/variant_annotation/annovar

#Set up new database
#source activate annovar
#gff3ToGenePred GCF_002863925.1_EquCab3.0_genomic.gff GCF_002863925.1_EquCab3.0_db/GCF_002863925.1_EquCab3.0_refGene.txt
#perl retrieve_seq_from_fasta.pl --format refGene --seqfile /home/mccuem/shared/Projects/HorseGenomeProject/Data/ibio_EquCab3/NCBI_reference/GCF_002863925.1_EquCab3.0_genomic.fna GCF_002863925.1_EquCab3.0_db/GCF_002863925.1_EquCab3.0_refGene.txt --out GCF_002863925.1_EquCab3.0_db/GCF_002863925.1_EquCab3.0_refGeneMrna.fa

cd /home/mccuem/shared/Projects/HorseGenomeProject/Data/ibio_EquCab3/variant_annotation/annovar/
#Gene based annotation
#1. Convert vcf
perl convert2annovar.pl -format vcf4 -allsample -include -withfreq EquCab3 ibio_union_gatk_bcftools_platypus.vcf.gz -outfile ../../ibio_output_files/ibio_union.avinput

perl annotate_variation.pl -buildver GCF_002863925.1_EquCab3.0 ../../ibio_output_files/ibio_union.avinput GCF_002863925.1_EquCab3.0_db --geneanno --hgvs -aamatrixfile example/grantham.matrix --out ../../ibio_output_files/ibio_union.annovar

