#!/bin/bash -l
#PBS -l nodes=1:ppn=4,walltime=24:00:00,mem=4g
#PBS -m abe
#PBS -M durwa004@umn.edu
#PBS -o $PBS_JOBID.ANNOVAR_intersect_NC_009153_3.out
#PBS -e $PBS_JOBID.ANNOVAR_intersect_NC_009153_3.err
#PBS -N ANNOVAR_intersect_NC_009153_3.pbs
#PBS -q mcqueue

cd /home/mccuem/shared/Projects/HorseGenomeProject/Data/ibio_EquCab3/ibio_output_files/joint_intersect

perl /home/mccuem/shared/Projects/HorseGenomeProject/Data/ibio_EquCab3/variant_annotation/annovar/convert2annovar.pl -format vcf4 -allsample -include -withfreq NC_009153_3_intersect_joint.vcf.gz --out annovar/NC_009153_3_annovar_intersect.avinput
perl /home/mccuem/shared/Projects/HorseGenomeProject/Data/ibio_EquCab3/variant_annotation/annovar/annotate_variation.pl -buildver GCF_002863925.1_EquCab3.0 annovar/NC_009153_3_annovar_intersect.avinput /home/mccuem/shared/Projects/HorseGenomeProject/Data/ibio_EquCab3/variant_annotation/annovar/GCF_002863925.1_EquCab3.0_db --geneanno --hgvs --aamatrixfile /home/mccuem/shared/Projects/HorseGenomeProject/Data/ibio_EquCab3/variant_annotation/annovar/example/grantham.matrix --out annovar/NC_009153_3_annovar_intersect
