#!/bin/bash -l
#PBS -l nodes=1:ppn=12,walltime=48:00:00,mem=12g
#PBS -m abe
#PBS -M durwa004@umn.edu
#PBS -o $PBS_JOBID.gatk_GenotypeGVCFs_SRR527520.out
#PBS -e $PBS_JOBID.gatk_GenotypeGVCFs_SRR527520.err
#PBS -N gatk_GenotypeGVCFs_SRR527520.pbs
#PBS -q small

cd /home/mccuem/shared/Projects/HorseGenomeProject/Data/ibio_EquCab3/ibio_output_files

/home/mccuem/shared/.local/conda/envs/HorseGenomeProject/bin/gatk/gatk --java-options "-Xmx4g" GenotypeGVCFs -R /home/mccuem/shared/Projects/HorseGenomeProject/Data/ibio_EquCab3/NCBI_reference/GCF_002863925.1_EquCab3.0_genomic.fna \ -V:SRR527520 ./ibio_output_files/SRR527520/SRR527520.gatk.gvcf.gz \ -o ibio_SRR527520.gatk.vcf.gz -nt 4
