#!/bin/bash -l
#PBS -l nodes=1:ppn=12,walltime=48:00:00,mem=12g
#PBS -m abe
#PBS -M durwa004@umn.edu
#PBS -o $PBS_JOBID.gatk_genotypegvcfs.out
#PBS -e $PBS_JOBID.gatk_genotypegvcfs.err
#PBS -N gatk_genotypegvcfs.pbs
#PBS -q small

cd /home/mccuem/shared/Projects/HorseGenomeProject/Data/ibio_EquCab3/ibio_output_files/gatk_joint

for i in NC_001640_1 NC_009160_3 NC_009161_3 NC_009162_3 NC_009163_3 NC_009164_3 NC_009165_3 NC_009166_3 NC_009167_3; do 
/home/mccuem/shared/.local/conda/envs/HorseGenomeProject/bin/gatk/gatk --java-options "-Xmx4g" GenotypeGVCFs -R /home/mccuem/shared/Projects/HorseGenomeProject/Data/ibio_EquCab3/ibio_output_files/GCF_002863925.1_EquCab3.0_genomic/GCF_002863925.1_EquCab3.0_genomic.fna -V ${i}.gvcf.gz -O gatk_joint_genotyped/${i}.genotyped.vcf.gz; done
