#!/bin/bash -l
#PBS -l nodes=1:ppn=12,walltime=48:00:00,mem=12g
#PBS -m abe
#PBS -M durwa004@umn.edu
#PBS -o $PBS_JOBID.union_platypus.out
#PBS -e $PBS_JOBID.union_platypus.err
#PBS -N union_platypus.pbs
#PBS -q small

cd /home/mccuem/shared/Projects/HorseGenomeProject/Data/ibio_EquCab3/AFIB_cases

java -Xmx4g -jar /home/mccuem/shared/.local/conda/envs/HorseGenomeProject/bin/GenomeAnalysisTK.jar -T CombineVariants -R /home/mccuem/shared/Projects/HorseGenomeProject/Data/ibio_EquCab3/NCBI_reference/GCF_002863925.1_EquCab3.0_genomic.fna \
  --variant:M10664 ./ibio_output_files/M10664/M10664.platypus.vcf.gz \
  --variant:M6117 ./ibio_output_files/M6117/M6117.platypus.vcf.gz \
  --variant:M6137 ./ibio_output_files/M6137/M6137.platypus.vcf.gz \
  --variant:M6138 ./ibio_output_files/M6138/M6138.platypus.vcf.gz \
  --variant:M8679 ./ibio_output_files/M8679/M8679.platypus.vcf.gz \
  --variant:M8738 ./ibio_output_files/M8738/M8738.platypus.vcf.gz \
  -o AFIB_cases_PL.vcf.gz -nt 4
