#!/bin/bash -l
#PBS -l nodes=1:ppn=8,walltime=36:00:00,mem=10gb
#PBS -m abe
#PBS -M durwa004@umn.edu
#PBS -q mcqueue


#NB for 10 horses took ~24 hours
source ~/.genomestrip_bashrc

cd /home/mccuem/shared/Projects/HorseGenomeProject/Data/EquCab3/dz_cases/CNVs/genomestrip/genomestrip_ibio/

runDir=/home/mccuem/shared/Projects/HorseGenomeProject/Data/EquCab3/dz_cases/CNVs/genomestrip/genomestrip_ibio/SVPreprocessing/

java -Xmx2g -cp ${SV_CLASSPATH} \
    org.broadinstitute.gatk.queue.QCommandLine \
    -S ${SV_DIR}/qscript/SVPreprocess.q \
    -S ${SV_DIR}/qscript/SVQScript.q \
    -cp ${SV_CLASSPATH} \
    -gatk ${SV_DIR}/lib/gatk/GenomeAnalysisTK.jar \
    -configFile ${SV_DIR}/conf/genstrip_parameters.txt \
    -tempDir ${SV_TMPDIR} \
    -R ${runDir}/../References/GCF_002863925.1_EquCab3.0_genomic.fasta \
    -runDirectory ${runDir} \
    -md ${runDir}/metadata \
    -I /home/mccuem/shared/Projects/HorseGenomeProject/scripts/EquCab3/ToolsforPMinthehorse/CNV_calling/ibio_bams.list \
    -bamFilesAreDisjoint true \
    -computeGCProfiles false \
    -computeReadCounts true \
    -jobLogDir ${runDir}/logs \
    -genderMaskBedFile ${runDir}../References/GCF_002863925.1_EquCab3.0_genomic.gendermask.bed \
    -ploidyMapFile ${runDir}../References/GCF_002863925.1_EquCab3.0_genomic.ploidymap.txt \
    -copyNumberMaskFile ${runDir}../References/GCF_002863925.1_EquCab3.0_genomic.gcmask.fasta \
    -genomeMaskFile ${runDir}../References/GCF_002863925.1_EquCab3.0_genomic.svmask.fasta \
    -readDepthMaskFile ${runDir}../References/GCF_002863925.1_EquCab3.0_genomic.rdmask.bed \
    -rmd ${runDir}../References/ \
    -jobRunner Drmaa \
      -gatkJobRunner Drmaa \
      -jobQueue mcqueue \
        -jobNative "-l nodes=1:ppn=4,walltime=02:00:00,mem=2gb" \
        -jobWrapperScript "source ~/.genomestrip_bashrc &&" \
    -maxConcurrentRun 6 \
    -run
