#!/bin/bash -l
#PBS -l nodes=1:ppn=8,walltime=12:00:00,mem=4g
#PBS -m abe
#PBS -M durwa004@umn.edu
#PBS -o $PBS_JOBID.bcftools_selectvariants_joint_unplaced.out
#PBS -e $PBS_JOBID.bcftools_selectvariants_joint_unplaced.err
#PBS -N bcftools_selectvariants_joint_unplaced.pbs
#PBS -q batch
source /home/mccuem/shared/.local/conda/bin/activate gatk4_4.1.0

cd /home/mccuem/shared/Projects/HorseGenomeProject/Data/ibio_EquCab3/ibio_output_files/joint_bcftools

gatk --java-options "-Xmx4g" SelectVariants -R /home/mccuem/shared/Projects/HorseGenomeProject/Data/ibio_EquCab3/ibio_output_files/GCF_002863925.1_EquCab3.0_genomic/GCF_002863925.1_EquCab3.0_genomic.fna --select-type-to-include SNP --select-type-to-include INDEL --select-type-to-include MNP -V unplaced.gvcf.gz -O unplaced.genotyped.vcf.gz
