#!/bin/bash -l
#PBS -l nodes=1:ppn=6,walltime=120:00:00,mem=60g
#PBS -m abe
#PBS -M durwa004@umn.edu
#PBS -q mcqueue


source /home/mccuem/shared/.local/conda/bin/activate ensembl-vep

#Set up database

#grep -v "#" GCF_002863925.1_EquCab3.0_genomic.gff | sort -k1,1 -k4,4n -k5,5n -t$'\t' | bgzip -c > GCF_002863925.1_EquCab3.0_genomic_VEP.gff.gz
#tabix -p gff GCF_002863925.1_EquCab3.0_genomic_VEP.gff.gz

cd /home/mccuem/shared/Projects/HorseGenomeProject/Data/ibio_EquCab3/AFIB_cases

vep -i ../../ibio_EquCab3/AFIB_cases/AFIB_cases_union_HC_ST_PL.vcf.gz --fasta /home/mccuem/shared/Projects/HorseGenomeProject/Data/ibio_EquCab3/NCBI_reference/GCF_002863925.1_EquCab3.0_genomic.fna --species GCF_002863925.1_EquCab3.0_genomic -o AFIB_cases_union_HC_ST_PL_ensembl-vep --check_existing -hgvs --gene_phenotype --regulatory --plugin SpliceRegion --custom ../variant_annotation/Ensembl-VEP/NCBI/GCF_002863925.1_EquCab3.0_genomic.modified.sorted.gff.gz,,gff,overlap,0


#Try with gtf. Ignore for now as above script seems to be working!
#vep -i ../../ibio_EquCab3/AFIB_cases/AFIB_cases_union_HC_ST_PL.vcf.gz --fasta /home/mccuem/shared/Projects/HorseGenomeProject/Data/ibio_EquCab3/NCBI_reference/GCF_002863925.1_EquCab3.0_genomic.fna --species GCF_002863925.1_EquCab3.0_genomic -o AFIB_cases_union_HC_ST_PL_ensembl-vep --gff ../variant_annotation/Ensembl-VEP/GCF_002863925.1_EquCab3.0_genomic_VEP.gtf.gz --check_existing -hgvs --gene_phenotype --regulatory --plugin SpliceRegion

#This is what worked for dz cases
#vep -i ../../dz_cases_union_HC_ST_PL.vcf.gz --fasta /home/mccuem/shared/Data/FASTAs/EquCab3/EquCab3_nucl.fasta --species equus_caballus --gtf EquCab3.gtf.gz -check_existing -hgvs --individual "all" --gene_phenotype --regulatory --plugin CADD --plugin Conservation,GERP_CONSERVATION_SCORE,mammals --plugin ExACpLI --plugin SpliceRegion --plugin REVEL --plugin Carol --plugin Condel,~/.vep/Plugins/config/Condel --plugin GO --plugin LoFtool -o dz_cases_CADD_Cons_ExACpLI_SR_REVEL_Carol_Condel_GO_LoFtool_individual_12192018


















