#!/bin/bash -l
#PBS -l nodes=1:ppn=1,walltime=24:00:00,mem=20g
#PBS -m abe
#PBS -M durwa004@umn.edu
#PBS -q small

cd /home/mccuem/shared/Projects/HorseGenomeProject/Data/ibio_EquCab3/AFIB_cases

java -Djava.io.tmpdir=/home/mccuem/shared/Projects/HorseGenomeProject/Data/temp_files -Xmx12g -jar /home/mccuem/shared/Projects/HorseGenomeProject/Data/ibio_EquCab3/variant_annotation/SnpEff/snpEff/SnpSift.jar filter "ANN[0].IMPACT has 'HIGH'" AFIB_cases_union_HC_ST_PL_snpeff.ann.vcf.gz > AFIB_cases_high_snpeff.ann.vcf

java -Djava.io.tmpdir=/home/mccuem/shared/Projects/HorseGenomeProject/Data/temp_files -Xmx12g -jar /home/mccuem/shared/Projects/HorseGenomeProject/Data/ibio_EquCab3/variant_annotation/SnpEff/snpEff/SnpSift.jar filter "ANN[0].IMPACT has 'MODERATE'" AFIB_cases_union_HC_ST_PL_snpeff.ann.vcf.gz > AFIB_cases_mod_snpeff.ann.vcf

java -Djava.io.tmpdir=/home/mccuem/shared/Projects/HorseGenomeProject/Data/temp_files -Xmx12g -jar /home/mccuem/shared/Projects/HorseGenomeProject/Data/ibio_EquCab3/variant_annotation/SnpEff/snpEff/SnpSift.jar filter "ANN[0].IMPACT has 'LOW'" AFIB_cases_union_HC_ST_PL_snpeff.ann.vcf.gz > AFIB_cases_low_snpeff.ann.vcf



source /home/mccuem/shared/.local/conda/bin/activate HorseGenomeProject
bgzip AFIB_cases_high_snpeff.ann.vcf
tabix AFIB_cases_high_snpeff.ann.vcf.gz
bgzip AFIB_cases_mod_snpeff.ann.vcf
tabix AFIB_cases_mod_snpeff.ann.vcf.gz
bgzip AFIB_cases_low_snpeff.ann.vcf
tabix AFIB_cases_low_snpeff.ann.vcf.gz
