#!/bin/bash -l
#PBS -l nodes=1:ppn=8,walltime=06:00:00,mem=22g
#PBS -m abe
#PBS -M durwa004@umn.edu
#PBS -q mcqueue

cd /home/mccuem/shared/Projects/HorseGenomeProject/Data/ibio_EquCab3/AFIB_cases

java -Djava.io.tmpdir=/home/mccuem/shared/Projects/HorseGenomeProject/Data/temp_files -Xmx12g -jar /home/mccuem/shared/Projects/HorseGenomeProject/Data/ibio_EquCab3/variant_annotation/SnpEff/snpEff/snpEff.jar -C /home/mccuem/shared/Projects/HorseGenomeProject/Data/ibio_EquCab3/variant_annotation/SnpEff/snpEff/snpEff.config EquCab3 AFIB_cases_union_HC_ST_PL.vcf.gz > AFIB_cases_union_HC_ST_PL_snpeff.ann.vcf -csvstats AFIB_cases_union_HC_ST_PL_snpeff_summary.csv -stats AFIB_cases_union_HC_ST_PL_snpeff_summary.html

source /home/mccuem/shared/.local/conda/bin/activate HorseGenomeProject

bgzip AFIB_cases_union_HC_ST_PL_snpeff.ann.vcf
tabix AFIB_cases_union_HC_ST_PL_snpeff.ann.vcf.gz


