#!/bin/bash -l
#PBS -l nodes=1:ppn=6,walltime=24:00:00,mem=2g
#PBS -m abe
#PBS -M durwa004@umn.edu
#PBS -o $PBS_JOBID.s3cmd_tidy.out
#PBS -e $PBS_JOBID.s3cmd_tidy.err
#PBS -N s3cmd_tidy.pbs
#PBS -q small

/usr/bin/s3cmd  --config /home/mccuem/shared/.local/.s3cfg mv s3://durwa004/230_horse_SNP_calling_December_2018.tar.gz s3://durwa004/EquCab2_analysis/
/usr/bin/s3cmd  --config /home/mccuem/shared/.local/.s3cfg mv s3://durwa004/230_horses_intersect_Aug.2019.tar.gz s3://durwa004/EquCab2_analysis/
/usr/bin/s3cmd  --config /home/mccuem/shared/.local/.s3cfg mv s3://durwa004/230_horses_vcfeval.tar.gz s3://durwa004/EquCab2_analysis/
/usr/bin/s3cmd  --config /home/mccuem/shared/.local/.s3cfg mv s3://durwa004/AFIB_cases_output_files.tar.gz s3://durwa004/dz_Cases/
/usr/bin/s3cmd  --config /home/mccuem/shared/.local/.s3cfg mv s3://durwa004/Canine_GB.tar.gz s3://durwa004/Dog_stuff/
/usr/bin/s3cmd  --config /home/mccuem/shared/.local/.s3cfg mv s3://durwa004/Done_makefiles_August_2019.tar.gz s3://durwa004/dz_cases/
/usr/bin/s3cmd  --config /home/mccuem/shared/.local/.s3cfg mv s3://durwa004/EMS_EquCab3_ST_by_chr.tar.gz s3://durwa004/EMS_EquCab3/
/usr/bin/s3cmd  --config /home/mccuem/shared/.local/.s3cfg mv s3://durwa004/EMS_EquCab3_bais.tar.gz s3://durwa004/EMS_EquCab3/
/usr/bin/s3cmd  --config /home/mccuem/shared/.local/.s3cfg mv s3://durwa004/EMS_EquCab3_bams.tar.gz s3://durwa004/EMS_EquCab3/
/usr/bin/s3cmd  --config /home/mccuem/shared/.local/.s3cfg mv s3://durwa004/EMS_EquCab3_gvcfs.tar.gz s3://durwa004/EMS_EquCab3/
/usr/bin/s3cmd  --config /home/mccuem/shared/.local/.s3cfg mv s3://durwa004/EMS_horses_EquCab3.tar.gz s3://durwa004/EMS_EquCab3/
/usr/bin/s3cmd  --config /home/mccuem/shared/.local/.s3cfg mv s3://durwa004/EquCab3_summary_files.tar.gz s3://durwa004/dz_cases/
/usr/bin/s3cmd  --config /home/mccuem/shared/.local/.s3cfg mv s3://durwa004/POP_December_2018.tar.gz s3://durwa004/EDCs_analysis/
/usr/bin/s3cmd  --config /home/mccuem/shared/.local/.s3cfg mv s3://durwa004/PPID_August_2019.tar.gz s3://durwa004/PPID_EquCab3/
/usr/bin/s3cmd  --config /home/mccuem/shared/.local/.s3cfg mv s3://durwa004/PPID_EquCab3_December_2018.tar.gz s3://durwa004/PPID_EquCab3/
/usr/bin/s3cmd  --config /home/mccuem/shared/.local/.s3cfg mv s3://durwa004/PPID_EquCab3_HC_ST_PL.tar.gz s3://durwa004/PPID_EquCab3/
/usr/bin/s3cmd  --config /home/mccuem/shared/.local/.s3cfg mv s3://durwa004/PPID_EquCab3_cases_1.tar.gz s3://durwa004/PPID_EquCab3/
/usr/bin/s3cmd  --config /home/mccuem/shared/.local/.s3cfg mv s3://durwa004/PPID_EquCab3_cases_2.tar.gz s3://durwa004/PPID_EquCab3/
/usr/bin/s3cmd  --config /home/mccuem/shared/.local/.s3cfg mv s3://durwa004/PPID_EquCab3_controls_1.tar.gz s3://durwa004/PPID_EquCab3/
/usr/bin/s3cmd  --config /home/mccuem/shared/.local/.s3cfg mv s3://durwa004/PPID_EquCab3_controls_2.tar.gz s3://durwa004/PPID_EquCab3/
/usr/bin/s3cmd  --config /home/mccuem/shared/.local/.s3cfg mv s3://durwa004/PPID_EquCab3_individual_g.vcfs.tar.gz s3://durwa004/PPID_EquCab3/
/usr/bin/s3cmd  --config /home/mccuem/shared/.local/.s3cfg mv s3://durwa004/PPID_EquCab3_mito.tar.gz s3://durwa004/PPID_EquCab3/
/usr/bin/s3cmd  --config /home/mccuem/shared/.local/.s3cfg mv s3://durwa004/PPID_EquCab3_union_gvcf.tar.gz s3://durwa004/PPID_EquCab3/
/usr/bin/s3cmd  --config /home/mccuem/shared/.local/.s3cfg mv s3://durwa004/PPID_ST_by_chromosome_EquCab3.tar.gz s3://durwa004/PPID_EquCab3/
/usr/bin/s3cmd  --config /home/mccuem/shared/.local/.s3cfg mv s3://durwa004/PUblic_genomes.tar.gz s3://durwa004/Public_genomes/
/usr/bin/s3cmd  --config /home/mccuem/shared/.local/.s3cfg mv s3://durwa004/Public_genomes_May_2018_10.tar.gz s3://durwa004/Public_genomes/
/usr/bin/s3cmd  --config /home/mccuem/shared/.local/.s3cfg mv s3://durwa004/Public_genomes_May_2018_11.tar.gz s3://durwa004/Public_genomes/
/usr/bin/s3cmd  --config /home/mccuem/shared/.local/.s3cfg mv s3://durwa004/Public_genomes_May_2018_12.tar.gz s3://durwa004/Public_genomes/
/usr/bin/s3cmd  --config /home/mccuem/shared/.local/.s3cfg mv s3://durwa004/Public_genomes_May_2018_13.tar.gz s3://durwa004/Public_genomes/
/usr/bin/s3cmd  --config /home/mccuem/shared/.local/.s3cfg mv s3://durwa004/Public_genomes_May_2018_14.tar.gz s3://durwa004/Public_genomes/
/usr/bin/s3cmd  --config /home/mccuem/shared/.local/.s3cfg mv s3://durwa004/Public_genomes_May_2018_15.tar.gz s3://durwa004/Public_genomes/
/usr/bin/s3cmd  --config /home/mccuem/shared/.local/.s3cfg mv s3://durwa004/Public_genomes_May_2018_16.tar.gz s3://durwa004/Public_genomes/
/usr/bin/s3cmd  --config /home/mccuem/shared/.local/.s3cfg mv s3://durwa004/Public_genomes_May_2018_17.tar.gz s3://durwa004/Public_genomes/
/usr/bin/s3cmd  --config /home/mccuem/shared/.local/.s3cfg mv s3://durwa004/Public_genomes_May_2018_18.tar.gz s3://durwa004/Public_genomes/
/usr/bin/s3cmd  --config /home/mccuem/shared/.local/.s3cfg mv s3://durwa004/Public_genomes_May_2018_19.tar.gz s3://durwa004/Public_genomes/
/usr/bin/s3cmd  --config /home/mccuem/shared/.local/.s3cfg mv s3://durwa004/Public_genomes_May_2018_2.tar.gz s3://durwa004/Public_genomes/
/usr/bin/s3cmd  --config /home/mccuem/shared/.local/.s3cfg mv s3://durwa004/Public_genomes_May_2018_20.tar.gz s3://durwa004/Public_genomes/
/usr/bin/s3cmd  --config /home/mccuem/shared/.local/.s3cfg mv s3://durwa004/Public_genomes_May_2018_21.tar.gz s3://durwa004/Public_genomes/
/usr/bin/s3cmd  --config /home/mccuem/shared/.local/.s3cfg mv s3://durwa004/Public_genomes_May_2018_22.tar.gz s3://durwa004/Public_genomes/
/usr/bin/s3cmd  --config /home/mccuem/shared/.local/.s3cfg mv s3://durwa004/Public_genomes_May_2018_23.tar.gz s3://durwa004/Public_genomes/
/usr/bin/s3cmd  --config /home/mccuem/shared/.local/.s3cfg mv s3://durwa004/Public_genomes_May_2018_24.tar.gz s3://durwa004/Public_genomes/
/usr/bin/s3cmd  --config /home/mccuem/shared/.local/.s3cfg mv s3://durwa004/Public_genomes_May_2018_25.tar.gz s3://durwa004/Public_genomes/
/usr/bin/s3cmd  --config /home/mccuem/shared/.local/.s3cfg mv s3://durwa004/Public_genomes_May_2018_26.tar.gz s3://durwa004/Public_genomes/
/usr/bin/s3cmd  --config /home/mccuem/shared/.local/.s3cfg mv s3://durwa004/Public_genomes_May_2018_3.tar.gz s3://durwa004/Public_genomes/
/usr/bin/s3cmd  --config /home/mccuem/shared/.local/.s3cfg mv s3://durwa004/Public_genomes_May_2018_4.tar.gz s3://durwa004/Public_genomes/
/usr/bin/s3cmd  --config /home/mccuem/shared/.local/.s3cfg mv s3://durwa004/Public_genomes_May_2018_5.tar.gz s3://durwa004/Public_genomes/
/usr/bin/s3cmd  --config /home/mccuem/shared/.local/.s3cfg mv s3://durwa004/Public_genomes_May_2018_6.tar.gz s3://durwa004/Public_genomes/
/usr/bin/s3cmd  --config /home/mccuem/shared/.local/.s3cfg mv s3://durwa004/Public_genomes_May_2018_7.tar.gz s3://durwa004/Public_genomes/
/usr/bin/s3cmd  --config /home/mccuem/shared/.local/.s3cfg mv s3://durwa004/Public_genomes_May_2018_8.tar.gz s3://durwa004/Public_genomes/
/usr/bin/s3cmd  --config /home/mccuem/shared/.local/.s3cfg mv s3://durwa004/Public_genomes_May_2018_9.tar.gz s3://durwa004/Public_genomes/
/usr/bin/s3cmd  --config /home/mccuem/shared/.local/.s3cfg mv s3://durwa004/References_EquCab3_old.tar.gz s3://durwa004/dz_cases/
/usr/bin/s3cmd  --config /home/mccuem/shared/.local/.s3cfg mv s3://durwa004/STB_TB_AFIB_August_2019.tar.gz s3://durwa004/dz_cases/
/usr/bin/s3cmd  --config /home/mccuem/shared/.local/.s3cfg mv s3://durwa004/Steve_dog_genomes_March_2019.tar.gz s3://durwa004/Dog_stuff/
/usr/bin/s3cmd  --config /home/mccuem/shared/.local/.s3cfg mv s3://durwa004/ToolsforPM_EC2_2M_data.tar.gz s3://durwa004/EquCab2_analysis/
/usr/bin/s3cmd  --config /home/mccuem/shared/.local/.s3cfg mv s3://durwa004/ToolsforPM_EC2_references.tar.gz s3://durwa004/EquCab2_analysis/
/usr/bin/s3cmd  --config /home/mccuem/shared/.local/.s3cfg mv s3://durwa004/ToolsforPM_EquCab2_vep.tar.gz s3://durwa004/EquCab2_analysis/
/usr/bin/s3cmd  --config /home/mccuem/shared/.local/.s3cfg mv s3://durwa004/ToolsforPM_paleomix.tar.gz s3://durwa004/EquCab2_analysis/
/usr/bin/s3cmd  --config /home/mccuem/shared/.local/.s3cfg mv s3://durwa004/ToolsforPM_sift4g.tar.gz s3://durwa004/VEP_old/
/usr/bin/s3cmd  --config /home/mccuem/shared/.local/.s3cfg mv s3://durwa004/Variant_interpretation.tar.gz s3://durwa004/VEP_old/
/usr/bin/s3cmd  --config /home/mccuem/shared/.local/.s3cfg mv s3://durwa004/breakdancer_Jan-Apr_2018.tar.gz s3://durwa004/dz_cases/
/usr/bin/s3cmd  --config /home/mccuem/shared/.local/.s3cfg mv s3://durwa004/cnmops.tar.gz s3://durwa004/dz_cases/
/usr/bin/s3cmd  --config /home/mccuem/shared/.local/.s3cfg mv s3://durwa004/dz_cases_August_2019.tar.gz s3://durwa004/dz_cases/
/usr/bin/s3cmd  --config /home/mccuem/shared/.local/.s3cfg mv s3://durwa004/dz_cases_VC_vcfs.tar.gz s3://durwa004/dz_cases/
/usr/bin/s3cmd  --config /home/mccuem/shared/.local/.s3cfg mv s3://durwa004/dz_cases_VEP_old_December_2018.tar.gz s3://durwa004/dz_cases/
/usr/bin/s3cmd  --config /home/mccuem/shared/.local/.s3cfg mv s3://durwa004/dz_cases_bams_December_2018.tar.gz s3://durwa004/dz_cases/
/usr/bin/s3cmd  --config /home/mccuem/shared/.local/.s3cfg mv s3://durwa004/dz_cases_gvcfs_December_2018.tar.gz s3://durwa004/dz_cases/
/usr/bin/s3cmd  --config /home/mccuem/shared/.local/.s3cfg mv s3://durwa004/fixvcfmissinggenoyptes_Equcab2.tar.gz s3://durwa004/EquCab2_analysis/
/usr/bin/s3cmd  --config /home/mccuem/shared/.local/.s3cfg mv s3://durwa004/genomestrip.tar.gz s3://durwa004/dz_cases/
/usr/bin/s3cmd  --config /home/mccuem/shared/.local/.s3cfg mv s3://durwa004/interval_bio_comparison.tar.gz s3://durwa004/ibio_analysis_2019/ibio_comparison/
/usr/bin/s3cmd  --config /home/mccuem/shared/.local/.s3cfg mv s3://durwa004/literature_search.tar.gz s3://durwa004/dz_cases/
/usr/bin/s3cmd  --config /home/mccuem/shared/.local/.s3cfg mv s3://durwa004/muscle_hypertrophy_literature_search.tar.gz s3://durwa004/dz_cases/
