#!/bin/bash -l
#PBS -l nodes=1:ppn=12,walltime=48:00:00,mem=4g
#PBS -m abe
#PBS -M durwa004@umn.edu
#PBS -o $PBS_JOBID.s3cmd_get_joint_gatk.out
#PBS -e $PBS_JOBID.s3cmd_get_joint_gatk.err
#PBS -N s3cmd_get_joint_gatk.pbs
#PBS -q small

cd /home/mccuem/shared/Projects/HorseGenomeProject/Data/ibio_EquCab3/ibio_output_files/gatk_joint

/usr/bin/s3cmd  --config /home/mccuem/shared/.local/.s3cfg get --recursive s3://mccue-lab/ibiodatatransfer2019/joint_gatk/

