#!/bin/bash -l
#PBS -l nodes=1:ppn=8,walltime=12:00:00,mem=4g
#PBS -m abe
#PBS -M durwa004@umn.edu
#PBS -o $PBS_JOBID.s3cmd_get_joint_gatk.out
#PBS -e $PBS_JOBID.s3cmd_get_joint_gatk.err
#PBS -N s3cmd_get_joint_gatk.pbs
#PBS -q mcqueue 

cd /home/mccuem/shared/Projects/HorseGenomeProject/Data/ibio_EquCab3/ibio_output_files/joint_gatk/

#module load parallel
#Can't get all because files are HUGE!
/usr/bin/s3cmd  --config /home/mccuem/shared/.local/.s3cfg get --recursive s3://mccue-lab/ibiodatatransfer2019/joint_gatk/

#Try for these chromosomes 1st:
#for i in NC_001640_1 NC_009160_3 NC_009161_3 NC_009162_3 NC_009163_3 NC_009164_3 NC_009165_3 NC_009166_3 NC_009167_3; do /usr/bin/s3cmd  --config /home/mccuem/shared/.local/.s3cfg get s3://mccue-lab/ibiodatatransfer2019/joint_gatk/${i}.gvcf.gz*; done

#Next 8
#for i in NC_009158_3 NC_009159_3 NC_009168_3 NC_009169_3 NC_009170_3 NC_009171_3 NC_009172_3 NC_009173_3; do /usr/bin/s3cmd  --config /home/mccuem/shared/.local/.s3cfg get s3://mccue-lab/ibiodatatransfer2019/joint_gatk/${i}.gvcf.gz; done
#for i in NC_009158_3 NC_009159_3 NC_009168_3 NC_009169_3 NC_009170_3 NC_009171_3 NC_009172_3 NC_009173_3; do /usr/bin/s3cmd  --config /home/mccuem/shared/.local/.s3cfg get s3://mccue-lab/ibiodatatransfer2019/joint_gatk/${i}.gvcf.g.tbiz; done

#Next 8
#for i in NC_009174_3 NC_009175_3 unplaced NC_009144_3 NC_009145_3 NC_009146_3 NC_009147_3 NC_009148_3; do /usr/bin/s3cmd  --config /home/mccuem/shared/.local/.s3cfg get s3://mccue-lab/ibiodatatransfer2019/joint_gatk/${i}.gvcf.gz; done
#for i in NC_009174_3 NC_009175_3 unplaced NC_009144_3 NC_009145_3 NC_009146_3 NC_009147_3 NC_009148_3; do /usr/bin/s3cmd  --config /home/mccuem/shared/.local/.s3cfg get s3://mccue-lab/ibiodatatransfer2019/joint_gatk/${i}.gvcf.gz.tbi; done

#Next 8:
#for i in NC_009149_3 NC_009150_3 NC_009151_3 NC_009152_3 NC_009153_3 NC_009154_3 NC_009155_3 NC_009156_3 NC_009157_3; do /usr/bin/s3cmd  --config /home/mccuem/shared/.local/.s3cfg get s3://mccue-lab/ibiodatatransfer2019/joint_gatk/${i}.gvcf.gz; done
#for i in NC_009149_3 NC_009150_3 NC_009151_3 NC_009152_3 NC_009153_3 NC_009154_3 NC_009155_3 NC_009156_3 NC_009157_3; do /usr/bin/s3cmd  --config /home/mccuem/shared/.local/.s3cfg get s3://mccue-lab/ibiodatatransfer2019/joint_gatk/${i}.gvcf.gz.tbi; done
