#!/bin/bash -l
#PBS -l nodes=1:ppn=4,walltime=48:00:00,mem=4g
#PBS -m abe
#PBS -M durwa004@umn.edu
#PBS -o $PBS_JOBID.union_joint_NC_009149_3.out
#PBS -e $PBS_JOBID.union_joint_NC_009149_3.err
#PBS -N union_joint_NC_009149_3.pbs
#PBS -q small

cd /home/mccuem/shared/Projects/HorseGenomeProject/Data/ibio_EquCab3/ibio_output_files/problem_chr/

java -Xmx4g -jar /home/mccuem/shared/.local/conda/envs/HorseGenomeProject/bin/GenomeAnalysisTK.jar -T CombineVariants -R /home/mccuem/shared/Projects/HorseGenomeProject/Data/ibio_EquCab3/ibio_output_files/GCF_002863925.1_EquCab3.0_genomic/GCF_002863925.1_EquCab3.0_genomic.fna --variant:bcftools NC_009149_3.bcftools.genotyped.vcf.gz --variant:gatk NC_009149_3.gatk.genotyped.vcf.gz -o NC_009149_3_union_joint.vcf.gz -nt 4 -genotypeMergeOptions UNSORTED
