#!/bin/bash -l
#PBS -l nodes=1:ppn=12,walltime=48:00:00,mem=12g
#PBS -m abe
#PBS -M durwa004@umn.edu
#PBS -o $PBS_JOBID.snpeff_annovar_union.out
#PBS -e $PBS_JOBID.snpeff_annovar_union.err
#PBS -N snpeff_annovar_union.pbs
#PBS -q small
module load bcftools

cd /home/mccuem/shared/Projects/HorseGenomeProject/Data/ibio_EquCab3/ibio_output_files/joint_intersect/SnpEff

for i in  NC_009156_3 NC_009160_3 NC_009174_3 NC_009150_3 NC_009161_3 NC_009148_3 NC_009144_3 NC_009153_3 NC_009175_3 NC_009154_3 NC_009158_3 NC_009159_3 unplaced NC_009167_3 NC_009163_3 NC_009166_3 NC_009162_3 NC_009157_3 NC_009164_3 NC_009172_3 NC_009147_3 NC_009169_3 NC_009173_3 NC_009152_3 NC_009146_3 NC_001640_1 NC_009151_3 NC_009155_3 NC_009168_3 NC_009165_3 NC_009170_3 NC_009171_3 NC_009145_3 NC_009149_3 ; do bcftools view ${i}_snpeff_intersect.coding.ann.vcf.gz -R ../union_SnpEff_annovar.txt > ${i}_union.vcf && /home/mccuem/durwa004/.conda/envs/ensembl-vep/bin/bgzip ${i}_union.vcf && /home/mccuem/durwa004/.conda/envs/ensembl-vep/bin/tabix ${i}_union.vcf.gz;done
