#!/bin/bash -l
#PBS -l nodes=1:ppn=16,walltime=12:00:00,mem=4g
#PBS -m abe
#PBS -M durwa004@umn.edu
#PBS -q lab

export PATH=/usr/home/mccuem/shared/.local/bin:$PATH

cd /home/mccuem/shared/Projects/HorseGenomeProject/Data/literature_search/CBAVD/

quickscrape --urllist eupmc_fulltext_html_urls.txt --scraper /home/mccuem/shared/Projects/HorseGenomeProject/Data/literature_search/CBAVD/generic_open.json --output CBAVD_eupmc_1