#!/bin/bash -l
#PBS -l nodes=1:ppn=4,walltime=24:00:00,mem=4g
#PBS -m abe
#PBS -M durwa004@umn.edu
#PBS -o $PBS_JOBID.SnpSift_filter_NC_009151_3.out
#PBS -e $PBS_JOBID.SnpSift_filter_NC_009151_3.err
#PBS -N SnpSift_filter_NC_009151_3.pbs
#PBS -q small

cd /home/mccuem/shared/Projects/HorseGenomeProject/Data/ibio_EquCab3/ibio_output_files/joint_intersect/SnpEff

java -Djava.io.tmpdir=/home/mccuem/shared/Projects/HorseGenomeProject/Data/temp_files -Xmx4g -jar /home/mccuem/shared/Projects/HorseGenomeProject/Data/ibio_EquCab3/variant_annotation/SnpEff/snpEff/SnpSift.jar filter "((ANN[0].IMPACT has 'HIGH') | (ANN[*].IMPACT = 'MODERATE') | (ANN[*].IMPACT = 'LOW'))" NC_009151_3_snpeff_intersect.ann.vcf.gz > NC_009151_3_snpeff_intersect.coding.ann.vcf
/home/mccuem/durwa004/.conda/envs/ensembl-vep/bin/bgzip NC_009151_3_snpeff_intersect.coding.ann.vcf
/home/mccuem/durwa004/.conda/envs/ensembl-vep/bin/tabix NC_009151_3_snpeff_intersect.coding.ann.vcf.gz
