#!/bin/bash -l
#PBS -l nodes=1:ppn=1,walltime=24:00:00,mem=20g
#PBS -m abe
#PBS -M durwa004@umn.edu
#PBS -q small

cd /home/mccuem/shared/Projects/HorseGenomeProject/Data/ibio_EquCab3/ibio_output_files/

((ANN[*].IMPACT = 'HIGH') | (ANN[*].IMPACT = 'MODERATE'))

java -Djava.io.tmpdir=/home/mccuem/shared/Projects/HorseGenomeProject/Data/temp_files -Xmx12g -jar /home/mccuem/shared/Projects/HorseGenomeProject/Data/ibio_EquCab3/variant_annotation/SnpEff/snpEff/SnpSift.jar filter "((ANN[0].IMPACT has 'HIGH') | (ANN[*].IMPACT = 'MODERATE') | (ANN[*].IMPACT = 'LOW'))" ibio_union.snpeff.ann.vcf.gz > ibio_union.high_mod_low.snpeff.ann.vcf

java -Djava.io.tmpdir=/home/mccuem/shared/Projects/HorseGenomeProject/Data/temp_files -Xmx12g -jar /home/mccuem/shared/Projects/HorseGenomeProject/Data/ibio_EquCab3/variant_annotation/SnpEff/snpEff/SnpSift.jar filter "((ANN[0].IMPACT has 'HIGH') | (ANN[*].IMPACT = 'MODERATE') | (ANN[*].IMPACT = 'LOW'))" ibio_intersect.snpeff.ann.vcf.gz > ibio_intersect.high_mod_low.snpeff.ann.vcf

source /home/mccuem/shared/.local/conda/bin/activate HorseGenomeProject
bgzip ibio_union.high_mod_low.snpeff.ann.vcf
tabix ibio_union.high_mod_low.snpeff.ann.vcf.gz
bgzip ibio_intersect.high_mod_low.snpeff.ann.vcf
tabix ibio_intersect.high_mod_low.snpeff.ann.vcf.gz
